#Requires -Version 5.1
<#
  loadorder.ps1 - apply collection order to Oblivion Remastered's FOUR separate
  ordering systems. Run after installs have settled.

    X:\MODDING\OBLIVION\tools\loadorder.ps1            report only
    X:\MODDING\OBLIVION\tools\loadorder.ps1 -Apply     write it

  THE RULE: position in 26_09_04_modlist.txt is the collection order. A mod
  later in that list beats an earlier one, so its meshes and textures win.

  THE FOUR SYSTEMS, and which direction wins in each:

   1 modlist.txt   MO2 file conflicts.   FIRST line = highest priority.
                   -> later in collection goes at the TOP.
   2 paks.txt      UE5 pak conflicts.    MO2 numbers these 8999 downward and
                   the LOWEST number wins, so LAST line wins.
                   -> later in collection goes at the BOTTOM.
   3 plugins.txt   ESP/ESM records.      Bethesda semantics, LAST loaded wins.
     loadorder.txt -> later in collection goes at the BOTTOM.
                   Vanilla head order is fixed and never reordered.
                   These two are a PAIR. plugins.txt says which plugins are
                   ACTIVE; loadorder.txt says what ORDER they load in, active
                   or not, and the game plugin calls setLoadOrder() from it
                   before it ever looks at plugins.txt. Write one without the
                   other and you enable everything in a stale order.
                   LOOT rewrites both afterwards, but it only has rules for a
                   handful of these mods - the rest keep the order they came
                   in with, which is why the baseline here is not cosmetic.
   4 mods.txt      UE4SS init order.     Not a conflict stack - left alone.

  Nothing is deleted. Every file is backed up before it is written.
#>

[CmdletBinding()]
param([switch]$Apply, [switch]$EnablePlugins)

$ErrorActionPreference = 'Stop'

$Instance   = 'X:\MODDING\OBLIVION\OBLIVION_REMASTERED'
$ModsDir    = Join-Path $Instance 'mods'
$ProfileDir = Join-Path $Instance 'profiles\Default'
$StateFile  = 'X:\MODDING\OBLIVION\data\nexus_state.json'
$Stamp      = Get-Date -Format 'yyyyMMdd-HHmmss'
$Utf8NoBom  = New-Object Text.UTF8Encoding $false
$mode = if ($Apply) { 'APPLY' } else { 'DRY RUN - pass -Apply to write' }

# The stock head of plugins.txt. Order is fixed by the game; never sort these.
$VanillaHead = @(
    'Oblivion.esm','DLCBattlehornCastle.esp','DLCFrostcrag.esp','DLCHorseArmor.esp',
    'DLCMehrunesRazor.esp','DLCOrrery.esp','DLCShiveringIsles.esp','DLCSpellTomes.esp',
    'DLCThievesDen.esp','DLCVileLair.esp','Knights.esp','AltarESPMain.esp',
    'AltarDeluxe.esp','AltarESPLocal.esp'
)
# Vortex pins these disabled at the bottom; the game does not load them normally.
$PinnedOff = @('AltarGymNavigation.esp','TamrielLeveledRegion.esp')

Write-Host "=== load order ($mode) ==="
Write-Host ""

if (Get-Process -Name 'ModOrganizer' -ErrorAction SilentlyContinue) {
    throw "Mod Organizer is running. Close it and re-run."
}
foreach ($p in @($ModsDir, $ProfileDir, $StateFile)) {
    if (-not (Test-Path -LiteralPath $p)) { throw "not found: $p" }
}

# ---- collection order -----------------------------------------------------
$state = @{}
(Get-Content -LiteralPath $StateFile -Raw | ConvertFrom-Json).PSObject.Properties |
    ForEach-Object { $state[$_.Name] = $_.Value }

$orderOf = @{}
foreach ($k in $state.Keys) {
    if ($state[$k].name) { $orderOf[$state[$k].name] = [int]$state[$k].order }
}

$folders = @(Get-ChildItem -LiteralPath $ModsDir -Directory | ForEach-Object { $_.Name })
$managed   = @($folders | Where-Object { $orderOf.ContainsKey($_) })
$unmanaged = @($folders | Where-Object { -not $orderOf.ContainsKey($_) })

Write-Host ("mods on disk: {0}   in collection: {1}   unmanaged: {2}" -f `
            $folders.Count, $managed.Count, $unmanaged.Count)
if ($unmanaged.Count) {
    Write-Host "  unmanaged (kept at lowest priority, order preserved):"
    $unmanaged | ForEach-Object { Write-Host "    $_" }
}
Write-Host ""

$ranked = @($managed | Sort-Object { $orderOf[$_] })    # ascending collection order

function Backup-File { param([string]$P)
    if ((Test-Path -LiteralPath $P) -and $Apply) {
        Copy-Item -LiteralPath $P -Destination "$P.bak-$Stamp" -Force } }

# ---- 1. modlist.txt : later in collection = TOP ---------------------------
Write-Host "--- 1. modlist.txt (MO2 conflict priority) ---"
$mlPath = Join-Path $ProfileDir 'modlist.txt'
$enabled = @{}
if (Test-Path -LiteralPath $mlPath) {
    foreach ($l in Get-Content -LiteralPath $mlPath) {
        if ($l -match '^([+\-])(.+)$') { $enabled[$Matches[2]] = ($Matches[1] -eq '+') }
    }
}
$topFirst = @($ranked); [array]::Reverse($topFirst)      # last collected -> first line

$ml = @('# This file was automatically generated by Mod Organizer.')
foreach ($n in $topFirst) {
    $on = if ($enabled.ContainsKey($n)) { $enabled[$n] } else { $true }
    $ml += $(if ($on) { "+$n" } else { "-$n" })
}
foreach ($n in $unmanaged) {
    $on = if ($enabled.ContainsKey($n)) { $enabled[$n] } else { $true }
    $ml += $(if ($on) { "+$n" } else { "-$n" })
}
Write-Host ("  {0} entries; top = {1}" -f ($ml.Count - 1), $(if ($topFirst.Count) { $topFirst[0] } else { '-' }))
Write-Host ("  bottom of collection = {0}" -f $(if ($topFirst.Count) { $topFirst[-1] } else { '-' }))
$disabled = @($enabled.Keys | Where-Object { -not $enabled[$_] })
if ($disabled.Count) { Write-Host ("  keeping {0} mod(s) disabled" -f $disabled.Count) }
Backup-File $mlPath
if ($Apply) { [IO.File]::WriteAllLines($mlPath, $ml, $Utf8NoBom) }
Write-Host ""

# ---- 2. paks.txt : later in collection = BOTTOM (lowest number = wins) ----
Write-Host "--- 2. paks.txt (UE5 pak conflicts) ---"
$pkPath = Join-Path $ProfileDir 'paks.txt'
$pakLines = @(); $pakCount = 0
foreach ($n in $ranked) {                       # ascending: earliest first
    $md = Join-Path $ModsDir $n
    $ps = @(Get-ChildItem -LiteralPath $md -Recurse -File -Filter '*.pak' -ErrorAction SilentlyContinue |
            Sort-Object Name)
    foreach ($p in $ps) {
        $stem = [IO.Path]::GetFileNameWithoutExtension($p.Name)
        if ($pakLines -notcontains $stem) { $pakLines += $stem; $pakCount++ }
    }
}
foreach ($n in $unmanaged) {                    # unmanaged first = loses
    $md = Join-Path $ModsDir $n
    foreach ($p in @(Get-ChildItem -LiteralPath $md -Recurse -File -Filter '*.pak' -ErrorAction SilentlyContinue | Sort-Object Name)) {
        $stem = [IO.Path]::GetFileNameWithoutExtension($p.Name)
        if ($pakLines -notcontains $stem) { $pakLines = @($stem) + $pakLines }
    }
}
$old = @(); if (Test-Path -LiteralPath $pkPath) { $old = @(Get-Content -LiteralPath $pkPath | Where-Object { $_.Trim() }) }
Write-Host ("  was {0} entries, now {1}" -f $old.Count, $pakLines.Count)
if ($pakLines.Count) {
    Write-Host ("  loses all conflicts : {0}" -f $pakLines[0])
    Write-Host ("  wins all conflicts  : {0}" -f $pakLines[-1])
}
Backup-File $pkPath
if ($Apply) { [IO.File]::WriteAllLines($pkPath, $pakLines, $Utf8NoBom) }
Write-Host ""

# ---- 3. plugins.txt + loadorder.txt : vanilla head fixed, rest ascending --
#
#   The OBR game plugin splits these two jobs, and writing only one is a trap:
#
#     plugins.txt    WHICH plugins are active. Read by readPluginList().
#     loadorder.txt  WHAT ORDER they load in, active or not. Read by
#                    readLoadOrderList(), and setLoadOrder() is called with it
#                    BEFORE plugins.txt is consulted.
#
#   So a run that enables 46 plugins in plugins.txt but leaves loadorder.txt
#   holding 15 stale lines gets everything switched on in the wrong order.
#   Both files are written together, always.
#
Write-Host "--- 3. plugins.txt + loadorder.txt (ESP activation and order) ---"
$plPath = Join-Path $ProfileDir 'plugins.txt'
$loPath = Join-Path $ProfileDir 'loadorder.txt'
$onNow = @{}
if (Test-Path -LiteralPath $plPath) {
    foreach ($l in Get-Content -LiteralPath $plPath) {
        if ($l -match '^\s*#') { continue }
        if ($l -match '^\s*\*?(.+\.es[pml])\s*$') { $onNow[$Matches[1]] = $true }
    }
}

# every esp/esm a managed mod ships, in collection order
$modOf = @{}
$byOrder = @()
# unmanaged mods first: lowest priority, but their plugins still need enabling
foreach ($n in ($unmanaged + $ranked)) {
    $md = Join-Path $ModsDir $n
    foreach ($e in @(Get-ChildItem -LiteralPath $md -Recurse -File -ErrorAction SilentlyContinue |
                     Where-Object { $_.Extension -in @('.esp','.esm') } | Sort-Object Name)) {
        if ($byOrder -notcontains $e.Name) { $byOrder += $e.Name; $modOf[$e.Name] = $n }
    }
}

$body = @()
foreach ($e in $byOrder) {
    if ($VanillaHead -contains $e) { continue }
    if ($PinnedOff   -contains $e) { continue }
    $body += $e
}

$head = @()
foreach ($v in $VanillaHead) {
    if ($v -eq 'AltarESPLocal.esp') { continue }   # listed by the game but ships no file
    $head += $v
}

# plugins.txt  = active set only
$pl = @('# This file was automatically generated by Mod Organizer.') + $head + $body

# loadorder.txt = EVERY plugin MO2 can see, in the same relative order, with the
# two the game ships disabled sitting where MO2 itself puts them: straight after
# the vanilla head. They stay out of plugins.txt, so they stay off.
$lo = @('# This file was automatically generated by Mod Organizer.') + $head + $PinnedOff + $body

$newly = @($body | Where-Object { -not $onNow.ContainsKey($_) })
Write-Host ("  {0} vanilla + {1} mod plugin(s)" -f $head.Count, $body.Count)
Write-Host ("  {0} not currently enabled" -f $newly.Count)
if ($body.Count) {
    Write-Host ("  loads first (overridden by all) : {0}   [{1}]" -f $body[0], $modOf[$body[0]])
    Write-Host ("  loads last  (wins all)          : {0}   [{1}]" -f $body[-1], $modOf[$body[-1]])
}
if (-not $EnablePlugins) {
    Write-Host "  NOT writing - pass -EnablePlugins to enable them all."
    Write-Host "  Then sort with LOOT, which understands real record conflicts."
} else {
    Backup-File $plPath
    Backup-File $loPath
    if ($Apply) {
        [IO.File]::WriteAllLines($plPath, $pl, $Utf8NoBom)
        [IO.File]::WriteAllLines($loPath, $lo, $Utf8NoBom)
    }
    Write-Host ("  plugins.txt   {0} active" -f ($pl.Count - 1))
    Write-Host ("  loadorder.txt {0} listed ({1} of them off)" -f ($lo.Count - 1), $PinnedOff.Count)
}
Write-Host ""

# ---- 4. report only -------------------------------------------------------
Write-Host "--- 4. mods.txt / mods.json (UE4SS) ---"
Write-Host "  init order, not a conflict stack - left alone."
Write-Host ""

if (-not $Apply) { Write-Host "Nothing changed. Re-run with -Apply." }
else { Write-Host "Done. Open MO2 and confirm the left pane and Paks tab look right." }
