@echo off
rem Generated by setup_magicloader.ps1 - launch this THROUGH MO2, never directly.
rem Run standalone it sees the bare game folder and cooks nothing.
setlocal
set "ML=C:\Program Files (x86)\Steam\steamapps\common\Oblivion Remastered\MagicLoader\mlcli.exe"
set "USERDIR=X:\MODDING\OBLIVION\logs\magicloader"
if not exist "%USERDIR%" mkdir "%USERDIR%"
rem No -g: v2.9 ignores it and derives the game from this exe location,
rem which is why the exe lives in the game folder rather than the mod.
"%ML%" -c -k -f -u "%USERDIR%"
exit /b %ERRORLEVEL%
